spring.application.name=api-gateway
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.port=${SERVER_PORT:8282}

spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://order-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://product-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=promotion-service
spring.cloud.gateway.routes[2].uri=lb://promotion-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/promotions/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

logging.level.root=INFO

eureka.instance.prefer-ip-address=true
