spring.application.name=order-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
server.port=${SERVER_PORT:8098}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.request.timeout.ms=15000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.acks=all

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:order-service}
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.properties.reconnect.backoff.ms=1000
spring.kafka.properties.reconnect.backoff.max.ms=10000

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

eureka.instance.prefer-ip-address=true

app.kafka.topics.order-created=${ORDER_CREATED_TOPIC:order_created}
app.kafka.topics.product-locked=${PRODUCT_LOCKED_TOPIC:product_locked}
