spring.datasource.url=jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/promotion?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:duc123}

eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://service-registry:8761/eureka/}
